# Generated by Django 2.1.5 on 2019-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_auto_20181229_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
