# Generated by Django 2.1.5 on 2019-06-12 19:00

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190612_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
