# Generated by Django 2.1.5 on 2019-06-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
    ]
